# Tutorial Regressão Linear Simples usando o Numpy e Libs externas

In [1]:
import numpy as np
from ml_libs import regressao_linear_simples
from ml_libs import metrics
from importlib import reload

In [2]:
reload(regressao_linear_simples)
reload(metrics)

<module 'ml_libs.metrics' from '/Users/regis/Dropbox/git/aulas-machine-learning-2019/ml_libs/metrics.py'>

## Linha reta de uma regressão linear simples



$$ y = w_0 + w_1 \cdot x $$

In [3]:
# $$ mean(x) = \frac { \sum_{i=1}^n { x_i } } { count(x) } $$

## Média

$$ mean(x) = \frac { \sum_{i=1}^n { x_i } } { count(x) } $$

In [4]:
x = np.array([ 1, 2, 4, 3, 5 ])
y = np.array([ 1, 3, 3, 2, 5 ])

In [5]:
model = regressao_linear_simples.RegressaoLinearSimples()

In [6]:
model.fit(x, y)

In [7]:
y_pred = model.predict(x)

In [8]:
y_pred

array([1.2, 2. , 3.6, 2.8, 4.4])

In [9]:
metrics.rmse(y, y_pred)

0.692820323027551

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [11]:
model2 = LinearRegression()

In [12]:
x_ = x.reshape((x.shape[0],1))
x_

array([[1],
       [2],
       [4],
       [3],
       [5]])

In [13]:
model2.fit(x_, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [14]:
y_pred_ = model2.predict(x_)
y_pred_

array([1.2, 2. , 3.6, 2.8, 4.4])

In [15]:
mse_ = mean_squared_error(y, y_pred_)
mse_

0.47999999999999987

In [16]:
np.sqrt(mse_)

0.6928203230275508